default_roles:
  - system
  - bat
  - docker
  - eza
  - fd
  - fish
  - fonts
  - fzf
  - git
  - lazydocker
  - lazygit
  - neovim
  - nvm
  - opencode
  - obsidian
  - pnpm
  - posting
  - ripgrep
  - sshfs
  - sshs
  - starship
  - tldr
  - wezterm
  - wireguard
