---
- name: "LAZYDOCKER | Download Latest Version JSON"
  ansible.builtin.uri:
    url: https://api.github.com/repos/jesseduffield/lazydocker/releases/latest
  register: lazydocker_latest_version_json
  changed_when: false
  check_mode: false

- name: "LAZYDOCKER | Registering lazydocker Latest Release"
  ansible.builtin.set_fact:
    lazydocker_latest_release: "{{ lazydocker_latest_version_json.json.tag_name }}"

- name: "LAZYDOCKER | Getting current lazydocker version"
  ansible.builtin.shell:
    cmd: >-
      /usr/local/bin/lazydocker --version | grep -oP '\K[0-9]+\.[0-9]+\.[0-9]+' | awk 'NR==1' | sed 's/^/v/'
  args:
    executable: /bin/bash
  register: current_lazydocker_version
  changed_when: false
  failed_when: false
  check_mode: false

- name: "LAZYDOCKER | Show current_lazydocker_version"
  ansible.builtin.debug:
    var: current_lazydocker_version.stdout

- name: "LAZYDOCKER | Show lazydocker_latest_release"
  ansible.builtin.debug:
    var: lazydocker_latest_release

- name: "LAZYDOCKER | Install"
  when: >-
    current_lazydocker_version.stdout | default('')
    != (lazydocker_latest_release | default(''))
  block:

    - name: "LAZYDOCKER | Define lazydocker_file"
      ansible.builtin.set_fact:
        lazydocker_file: "lazydocker_{{ lazydocker_latest_release | regex_replace('^.', '') }}_Linux_x86_64"

    - name: "LAZYDOCKER | Ensure clean download destination"
      ansible.builtin.file:
        path: "/tmp/{{ lazydocker_file }}.tar.gz"
        state: absent
      become: true

    - name: "LAZYDOCKER | Downloading lazydocker Release"
      ansible.builtin.get_url:
        url: "https://github.com/jesseduffield/lazydocker/releases/download/{{ lazydocker_latest_release }}/{{ lazydocker_file }}.tar.gz"
        dest: /tmp/
        mode: "0644"
        force: true
      notify:
        - Cleanup lazydocker downloaded tar

    - name: "LAZYDOCKER | Ensure clean extraction destination"
      ansible.builtin.file:
        path: "/tmp/lazydocker"
        state: absent
      become: true

    - name: "LAZYDOCKER | Extract lazydocker tar file"
      ansible.builtin.unarchive:
        src: "/tmp/{{ lazydocker_file }}.tar.gz"
        dest: /tmp

    - name: "LAZYDOCKER | Remove any current lazydocker installations"
      ansible.builtin.file:
        path: /usr/local/bin/lazydocker
        state: absent
      become: true

    - name: "LAZYDOCKER | Install lazydocker"
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/lazydocker
        dest: /usr/local/bin/
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        force: true
        mode: "0755"
      become: true
      notify:
        - Remove extracted lazydocker directory
