---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists

- name: Check if .ssh/config exists
  stat:
    path: "/home/{{ ansible_facts['env']['USER'] }}/.ssh/config"
  register: stat_result
  changed_when: false

- name: Create the file, if it doesn't exist already
  file:
    path: "/home/{{ ansible_facts['env']['USER'] }}/.ssh/config"
    state: touch
  when: not stat_result.stat.exists
  become: true
