---
- name: "Check if nvm.fish is installed"
  ansible.builtin.command:
    cmd: >-
      grep -c 'jorgebucaran/nvm.fish'
      /home/{{ ansible_facts['env']['USER'] }}/.config/fish/fish_plugins
  register: grep_result
  changed_when: false
  failed_when: false

- name: "Install required Node versions"
  when: grep_result.rc == 0
  block:
    - name: "Install required Node versions"
      ansible.builtin.shell: fish -c "nvm install {{ item }}"
      register: install_result
      with_items:
        - lts
      changed_when: "'Installing' is in install_result.stdout"

    - name: "Get the latest LTS version of Node.js"
      ansible.builtin.shell: fish -c "nvm list-remote lts | tail -n 1"
      register: latest_lts_version
      changed_when: false
      failed_when: >-
        latest_lts_version.rc != 0
        or not latest_lts_version.stdout | regex_search('\w+\.\w+\.\w+')

    - name: "Get current Node version"
      ansible.builtin.shell: fish -c "nvm current"
      register: current_node_version
      changed_when: false
      failed_when: false

    - name: "Use latest LTS version of Node.js"
      ansible.builtin.shell: fish -c "nvm use lts"
      when: >-
        current_node_version.stdout
        != (latest_lts_version.stdout
            | regex_search('v[0-9]+\.[0-9]+\.[0-9]+') | first)
      changed_when: false

    - name: "Get current default Node version"
      ansible.builtin.shell: fish -c "echo $nvm_default_version"
      register: current_default_version
      changed_when: false
      failed_when: false

    - name: "Set default Node version"
      ansible.builtin.shell: fish -c "set --universal nvm_default_version lts"
      when: current_default_version.stdout != "lts"
      changed_when: false
