#!/bin/bash

ubuntu_setup() {
  # Source os-release to get VERSION_ID
  if [ -f /etc/os-release ]; then
    source /etc/os-release
  fi

  if ! dpkg -s ansible >/dev/null 2>&1; then
    __task "Installing Ansible (This may take a few minutes)"
    _cmd "sudo apt-get update"
    _cmd "sudo apt-get install -y software-properties-common"
    _cmd "sudo apt-add-repository -y ppa:ansible/ansible"
    _cmd "sudo apt-get update"
    _cmd "sudo apt-get install -y ansible"
    _cmd "sudo apt-get install -y python3-argcomplete"
  fi
  if ! dpkg -s python3 >/dev/null 2>&1; then
    __task "Installing Python3"
    _cmd "sudo apt-get install -y python3"
  fi

  local UBUNTU_MAJOR_VERSION=$(echo "$VERSION_ID" | cut -d. -f1)
  if [ "$UBUNTU_MAJOR_VERSION" -le 22 ] 2>/dev/null; then
    if ! dpkg -s python3-pip >/dev/null 2>&1; then
      __task "Installing Python3 Pip"
      _cmd "sudo apt-get install -y python3-pip"
    fi
    if ! pip3 list | grep watchdog >/dev/null 2>&1; then
      __task "Installing Python3 Watchdog"
      _cmd "sudo apt-get install -y python3-watchdog"
    fi
  fi
}

arch_setup() {
  if ! [ -x "$(command -v ansible)" ]; then
    __task "Installing Ansible (This may take a few minutes)"
    _cmd "sudo pacman -Syu --noconfirm"
    _cmd "sudo pacman -S --noconfirm ansible"
    _cmd "sudo pacman -S --noconfirm python-argcomplete"
    # _cmd "sudo activate-global-python-argcomplete3"
  fi
  if ! pacman -Q python3 >/dev/null 2>&1; then
    __task "Installing Python3"
    _cmd "sudo pacman -S --noconfirm python3"
  fi
  if ! pacman -Q python-pip >/dev/null 2>&1; then
    __task "Installing Python3 Pip"
    _cmd "sudo pacman -S --noconfirm python-pip"
  fi
  if ! pip3 list | grep watchdog >/dev/null 2>&1; then
    __task "Installing Python3 Watchdog"
    _cmd "sudo pacman -S --noconfirm python-watchdog"
  fi

  # if ! pacman -Q openssh >/dev/null 2>&1; then
  #   __task "Installing OpenSSH"
  #   _cmd "sudo pacman -S --noconfirm openssh"
  # fi
}
