---
- name: Obsidian | Detect if Desktop Environment"
  ansible.builtin.set_fact:
    ansible_host_is_desktop_environment: "{{ lookup('env', 'XDG_CURRENT_DESKTOP') }}"

- name: "Obsidian | Install"
  community.general.flatpak:
    name: "md.obsidian.Obsidian"
    state: present
  when:
    - not ansible_host_environment_is_wsl
    - ansible_host_is_desktop_environment | bool

- name: Check if $HOME/vaults exists
  stat:
    path: "{{ ansible_facts['user_dir'] }}/vaults"
  register: vaults_dir_stat
  changed_when: false

- name: Create $HOME/vaults if it doesn't exist
  file:
    path: "{{ ansible_facts['user_dir'] }}/vaults"
    state: directory
    mode: '0755'
  when: not vaults_dir_stat.stat.exists

- name: Create symlinks for each vault
  file:
    src: "{{ item.path }}"
    dest: "{{ ansible_facts['user_dir'] }}/vaults/{{ item.name }}"
    state: link
  with_items: "{{ obsidian.vaults }}"
  when: obsidian.vaults is defined

- name: Copy Templates to each vault
  ansible.builtin.copy:
    dest: "{{ ansible_facts['user_dir'] }}/vaults/{{ item.name }}/Templates/"
    src: "{{ role_path }}/files/Templates/"
    force: true
  with_items: "{{ obsidian.vaults }}"
  when: obsidian.vaults is defined

- name: Export obsidian.default_vault to fish config
  blockinfile:
    prepend_newline: true
    path: "{{ ansible_facts['user_dir'] }}/.config/fish/parts/obsidian.fish"
    block: |
      # define Obsidian directory
      export OBSIDIAN_VAULT_DIR={{ansible_facts['user_dir']}}/vaults/{{ obsidian.default_vault }}
    marker: "# {mark} ANSIBLE BLOCK: {{ role_name }} | Export obsidian.default_vault to fish config"
    create: yes
    state: present
  when: obsidian.default_vault is defined
