---
- name: "Go-Lang | Install dependencies"
  ansible.builtin.apt:
    pkg:
      - 'curl'
      - 'gcc'
      - 'git'
      - 'findutils'
      - 'make'
      - 'rsync'
      - 'tar'
      - 'jq'
    state: present
  register: apt_result
  become: true
  until: apt_result is success
  retries: 1
  delay: 2
