- name: Install fd-find
  become: true
  ansible.builtin.package:
    state: present
    name: fd-find

- name: Create link fd to fdfind in Debian
  become: true
  ansible.builtin.file:
    src: '/usr/bin/fdfind'
    dest: '/usr/bin/fd'
    state: link
  when: ansible_os_family == 'Debian'
